### ISSUE TITLE
Cache verification key in CLI

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/zkapp-cli#158]
When you go through the `zk deploy` flow multiple times, it's annoying that the veriffication key is rebuilt every time, which takes 1-2 minutes

Would be nice to cache the veriffication key

TBD: how do we handle cache invalidation / enable rebuilding when it's needed. Ideally, we detect when the vk changed from a quick-to-compute hash of the circuit, but that would require more work on the snarkyjs side.

Some ideas for what we could do now:
* never invalidate the cache, expose an explicit --rebuild option to `zk deploy`
* separate compiling into its own command, `zk compile`, which never uses a cache, and let `zk deploy` just depend on the output it creates -- that way, rebuilding is always an explicit operation

**Comment by jasongitmail** [comment]
In what situations would when a dev would need to sit through generating & deploying the _same_ verification key? Only if deploying once to network A (i.e. Testnet) and again to network B (i.e. Mainnet)?

**Comment by jasongitmail** [comment]
Actually I found an answer: If an error occurs during deployment (i.e. tx relayer unavailable, etc) then it would be convenient to have that cached for when re-trying again.

**Comment by mitschabaude** [comment]
Yes, anything were you get off the happy path. For example: Something in your code prevents deploy from working, and you want to iterate on that. Like the error that Serhii reported recently, it probably happened in the `Mina.transaction` block, which is (has to be) after compiling. Then, with every fix you try, you have to wait 2 minutes to see if it works. This is not a theoretical problem, it was a pain for me and there were users in discord complaining about this too.

There are also cases where you break out of the flow even if no error occurs. For example, you get to the point where you have to set the transaction fee, but you are not sure what fee you should use, so you Ctrl-C and do it again later. These things happen all the time.

**Comment by mitschabaude** [comment]
@bkase to write RFC

**Comment by jasongitmail** [comment]
We could also store the digest values inside of a `digests` property or similar, within `build.json`.

**Comment by bkase** [comment]
>  We could also store the digest values inside of a digests property or similar, within build.json. Feels like a natural location given we store other computed values there already.

The only risk is corruption if there are multiple writes at the same time to this file, but as long as we're careful this should work 👍

**Comment by jasongitmail** [comment]
true, but should be ok b/c we should gather all digests then write to disk once

**Comment by jasongitmail** [comment]
@ymekuria Looks like we can't use `build.json` after all because it is clobbered each time `deploy` is run here: https://github.com/o1-labs/zkapp-cli/blob/e1f89a47c224149129d7339085c1559d991f9fe9/src/lib/deploy.js#L92-L103

But we could add a `build/cache.json` file and store the cache-related data there. I'd probably just nest both under the smart contract name:

```json
{
  "<smartContractNameA>": {
    "digest": "abc",
    "verificationKey": "abc",
  },
  "<smartContractnameB>": {
    "digest": "abc",
    "verificationKey": "abc",
  }
}
```

Note that there is a known limitation of `build.json`, and this caching code by extension, in that we assume all smart contracts in a project have unique names. It's probably acceptable, but we could warn people if their project contains >1 smart contract with the same name; I'll create an issue to track this.

**Comment by ymekuria** [comment]
> But we could add a `build/cache.json` file and store the cache-related data there. I'd probably just nest both under the smart contract name:

Good catch about build.json. I like the idea of adding a cache.json file.

**Comment by ymekuria** [comment]
@jasongitmail It looks like we can't put cache.json file in the build directory because the directory is emptied every time deploy is run here: 

https://github.com/o1-labs/zkapp-cli/blob/e1f89a47c224149129d7339085c1559d991f9fe9/src/lib/deploy.js#L87-L90

We can add the cache.json file to the root of the template at the same level as the config.json and add it to gitignore.

**Comment by mitschabaude** [comment]
@ymekuria, I think we should just not empty the build directory in that case :D instead we could delete everything in there except cache.json

FWIW, inside `keys` feels wrong to me, because the verification "key" isn't a key in the usual sense of the term and putting it there would only contribute further to this confusion :D

**Comment by jasongitmail** [comment]
The keys dir isn't the right location because this is a file that a dev should never really see.

+1 for changing line 88 to delete all files except the cache.json. I'd suggest reading `cache.json` into memory, empty the dir, and output `cache.json` again.
