### ISSUE TITLE
Add a way to list available configurations

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/zkapp-cli#236]
It will be helpful to have a way to list currently available configurations, since we have a way to add new configs.

**Comment by mitschabaude** [comment]
Isn't looking at the `config.json` enough?

**Comment by shimkiv** [comment]
We can say the same for pretty much anything :). Like having an example of `config.json` file why we even need current `zk config` configurator?
The point here in more pleasant config visualisation within the shell especially in case if that config will start to have complex tree.

**Comment by jasongitmail** [comment]
> We can say the same for pretty much anything :). Like having an example of config.json file why we even need current zk config configurator?

This serves a purpose because provides guidance to users on what data to enter, which is especially important when adding the first item to the config because no previous entires exist to look at.

Currently, if a dev types `zk config`, the current config will be output. It also gives you the ability to add an additional item to this config or you can press "ctrl+c" to exit. I feel like this is sufficient, but interested to hear your suggestion.

@shimkiv Can you suggest what you desired behavior would look like please?

**Comment by jasongitmail** [comment]
Reviewing with Yoni. We believe this to be stale and non-actionable because `zk config` shows existing configs. Feel free to reopen with a comment.
