### ISSUE TITLE
RFC to show a warning when user must upgrade their zkapp-cli version

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/zkapp-cli#247]
**Current**

During breaking upgrades to zkApps protocol (i.e. during QANet and Testnet) both the protocol and SnarkyJS need to advance to be compatible with one another. Developers who don't upgrade their zkapp-cli after the protocol receives such upgrades, can experience an error message about the "fee paying account not being found". The error message is unclear and leaves users without guidance for this situation.

**Proposal**

- To address this, we'd like to check the latest version of zkapp-cli available on NPM and show a warning guiding user to upgrade their zkapp-cli via `npm upgrade -g zkapp-cli && npm update snarkyjs`. _(Edit: Updated the command per comments below.)_

Aspects to discuss:
- While SnarkyJS and the zkApp CLI have a major version of 0, we can consider changes to the minor version of the zkapp-cli to represent breaking changes. When SnarkyJS and the zkApp have a major version of 1 or higher, we can consider changes to the major version of the zkapp-cli to be breaking, following semver.
- **Should this occur during every invocation of `zk` or only during `zk deploy`?**  Running `zk deploy` implies that the developer has access to the internet (which is not required for commands such as `zk project`). `zk deploy` is also the command where a user would encounter this error message, and never on other commands. For these two reasons, I suggest we implement this check as a first step of the `zk deploy` and NOT for any other commands within the zkApp CLI.

Behavior:
- When `zk deploy` is run, fetch current version from NPM for `zkapp-cli`.
-  If version is deemed breaking from the current CLI version (see above), show warning message explaining and guiding dev to run `npm update -g zkapp-cli`.
- Exit process and do not continue deployment.

**Comment by mitschabaude** [comment]
Thanks for writing this up!

> * When zk deploy is run, fetch current version from NPM for `zkapp-cli`.
> * If version is deemed breaking from the current CLI version (see above), show warning message explaining and guiding dev to `run npm update -g zkapp-cli.`
> * Exit process and do not continue deployment.

In step 2, while there is a chance that updating the zkapp-CLI fixes a problem, in many cases it's actually snarkyjs that needs updating. Since the CLI takes snarkyjs from the user project (it has to), updating the CLI alone wouldn't fix it. So I propose to also do `npm update snarkyjs`. I think we can assume that we're inside an npm project since, IIRC, the CLI already fails fast if it doesn't think it's inside a CLI-generated project.

That raises another question: Do we also need to check for the snarkyjs version? Or will "minor version change in snarkyjs" always imply "minor version change in the CLI", so checking the CLI version is enough?

Another proposal: Updating an npm package without user consent might be seen as intrusive. For example, some users might want to understand what code they're downloading and executing before doing so. Therefore, I think we should print a message saying something like
```
There's a new minor zkapp-cli version XXX. Your current version is XXX.
Since the minor version changed, the CLI will likely not be compatible with
the network your trying to deploy your zkApp to.

Do you want to update the zkapp-cli now?

[x] Yes, update the CLI with npm
[ ] Don't update but remind me later
[ ] No, don't update and don't ask again

Press ↑ and ↓ to switch, [enter] to accept
```

**Comment by jasongitmail** [comment]
> npm update -g zkapp-cli && npm update snarkyjs.
+1 this is important. Updating the CLI would fix it for newly created projects only

I'm with not exiting the process. The only downside is that it will feel messier to the dev since they'll encounter two error messages, where the 2nd one is one that isn't useful at all.  

If we're following the versioning pattern described for breaking changes, an error would be expected to always occur if our versioning warning error message is shown. So that's a bit of a downside--increasing the noise with one unhelpful error message. But no strong feels on it

**Comment by ymekuria** [comment]
This is great @jasongitmail.
> So I propose to add that to the warning message and tell them to do something like `npm update -g zkapp-cli && npm update snarkyjs`.

+1 on guiding to update the zkapp-cli and SnarkyJS.

**Comment by ymekuria** [comment]
I'm torn on if we should exit the process if the user has an old version of the CLI. I'm leaning towards not exiting the process and showing the warning if the deployment fails.

**Comment by jasongitmail** [comment]
After typing my response above and thinking about it more, I'm leaning back slightly toward exiting the process because: 1.) we will be following a pattern with our versioning that should allow us to have a quality signal for breaking changes, 2.) the failed deployment error message that a user would see by continuing adds noise and confusion to the situation for the dev. It turns our clear guidance into something less clear.

**Comment by mitschabaude** [comment]
I'm also fine with exiting the process. In this early phase, with snarkyjs being very unstable, it doesn't hurt if we soft-force users to always be on the latest version. In a more stable future, it's also fine because major upgrades will become rare.

To get a good signal, we'll have to make the cli version track compatibility of snarkyjs with the current network, bumping the version even if the cli didn't change. But that's ok I think!
