### ISSUE TITLE
Does SnarkyJS still need to be a peer dep? 

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/zkapp-cli#271]
iirc we switched to using a peer dep b/c the CLI needed SnarkyJS for deployment and this confilcted with the user's SnarkyJS.

But we now use the user's SnarkyJS for deployment. If we can switch back to a regular dep inside the `project-ts` project template, then `zk system` would be able to show SnarkyJS' version. But envinfo, which we use for `zksystem`, cannot list a peer dependency's version.

The todo here is to test create a project, switch SnarkyJS to a regular dep, npm install, and try to deploy it. If it works, we can switch back to a regular dependency.

**Comment by mitschabaude** [comment]
No, unfortunately we switched to peer dep for a different reason. We did it so that UI (or other) projects can import both snarkyjs and the smart contract, without creating a situation where there are two versions of snarkyjs around (it deeply breaks snarkyjs if it's imported twice, bc it has a lot of global state, which is very much core to the imperative API we have for building circuits / transactions).

I think we could identify the need to update snarkyjs with a homegrown solution.

For classical projects (no ui / monorepo) we could take the "version range" in `package.json` as a hint and ask the user to update to a newer version range. Example: if we see that the project version is `"^0.6.0"` we could suggest a command to the user which would update that to `"^0.7.2"`.

For monorepo projects, we could set it up so that snarkyjs is already installed as a normal dep in the ui project, and find out the exact version (like, by checking `package-lock.json` or `node_modules/snarkyjs/package.json`) in that project.
