### ISSUE TITLE
Time out when gittar cache warming hangs

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/zkapp-cli#314]
It seems that github can be very unresponsive sometimes, which will cause installation (upgrade) of the zkapp CLI or its examples to hang (in my experience, sometimes indefinitely) during the step `Warm cache for project template.`. Since warming the cache is not a must have, we should have a timeout on this operation, so the user can proceed with installation when it doesn't work.

**Comment by jasongitmail** [comment]
To research to confirm why this is occurring .

**Comment by nicc** [comment]
@ymekuria please write up a mini rfc

**Comment by ymekuria** [comment]
**Description of Problem** 

Sometimes the installation or upgrade of  the `zkapp-cli` hangs during the `Warm cache for project template` step. This is caused in the `postinstall.js` file when a network request is made by gittar to fetch the `zkapp-cli` templates and examples from github [here](https://github.com/o1-labs/zkapp-cli/blob/main/src/postinstall.js#L59).

**Proposed Solution**

Warming the cache isn't necessary for a user to perform an upgrade or installation. We should add a timeout to the gittar fetch request so a user can proceed with the installation or upgrade if it has not completed after a certain amount of time. 

**Approach** 

We can create a helper function that takes in the gittar fetch request and the max time limit in milliseconds to wait for the request before continuing as arguments, and returns null if the gittar fetch request was unsuccessful .

`warmGittarCacheInTimeLimit(timeLimit, request )`  

In this function we can create a gittarTimeoutPromise that resolves to null(can be anything) after the `maxTimeLimit`.

```
  const gittarTimeoutPromise = new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(null);
    }, timeLimit);
  }); 
```

We can pass the `gittarTimeoutPromise` and the gittar fetch request into [promise.race](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race)(or promise.any). Promise.race will return the value of the first promise that settles. If the timeOutPromise settles first ie. the gittar fetch isn't successful in the `maxTimeLimit `, the response will return null. If the returned response from `warmGittarCacheInTimeLimit` is null, we can return from the `warmGittarCache` function and the installation will continue. This helper function can be made generic and used in elsewhere. The function would look something like this.

```
async function warmGittarCacheInTimeLimit(timeLimit, gittarFetch) {
  let gittarTimeout;
  const response = await Promise.race([gittarFetch, gittarTimeoutPromise]);

  const gittarTimeoutPromise = new Promise((resolve, reject) => {
   gittarTimeout = setTimeout(() => {
      resolve(null);
    }, timeLimit);
  });

  if (gittarTimeout) {
    // clean up the timeout
    clearTimeout(gittarTimeout);
  }
  return response;
}
```
@jasongitmail @nicc @mitschabaude

**Comment by mitschabaude** [comment]
Sounds great!

**Comment by ymekuria** [comment]
The remaining question is the appropriate `maxTimLimit` that provides a good ux but also is enough time for the warm cache to complete in the majority of cases.

**Comment by jasongitmail** [comment]
It's worth mentioning that we know the hang occurs in `postinstall.js`, but do we have data to support that it's gittar vs `npm run add <pkg>` hanging, to be certain of the root cause? 

For better visibility, we may want to also add a console log [here](https://github.com/o1-labs/zkapp-cli/blob/main/src/postinstall.js#L46) after Line 45 and before Line 46 console logging which NPM package is being added to cache, and again between [Line 58 & 59](https://github.com/o1-labs/zkapp-cli/blob/main/src/postinstall.js#L59). 

That said, the proposed solution seems worth doing b/c there's a good chance it's happening during the gittar fetch. But I'd recommend we also adding logging, so we can validate if this hypothesis was right.

**Comment by ymekuria** [comment]
> For better visibility, we may want to also add a console log [here](https://github.com/o1-labs/zkapp-cli/blob/main/src/postinstall.js#L46) after Line 45 and before Line 46 console logging which NPM package is being added to cache, and again between [Line 58 & 59](https://github.com/o1-labs/zkapp-cli/blob/main/src/postinstall.js#L59).

That is a good idea to add logs for more visibility. 

> but do we have data to support that it's gittar vs npm run add <pkg> hanging, to be certain of the root cause?

Another data point - When @mitschabaude first brought up this issue, the cli was hanging after the `Warm cache for project template` console.log on [line 55](https://github.com/o1-labs/zkapp-cli/blob/main/src/postinstall.js#L55). We were able to resolve the hanging by commenting out [line 59](https://github.com/o1-labs/zkapp-cli/blob/main/src/postinstall.js#L59).

**Comment by nicc** [comment]
Sounds good!

What are the implications of not warming the cache on installation? Like what state is it in if somebody installs "successfully" without warming the cache? Will it just fetch the templates the first time a project is generated?

Aside: it's funny, I read this and see the equivalent async clojure code for this `any` promise timeout mechanism. Wonder how long that'll take to fade 😄

**Comment by jasongitmail** [comment]
@nicc project creation will be slower and will require internet (i.e. can't do it on a train in a tunnel). I had offline project creation working initially ages ago, but we have since made some changes and I haven't prioritized maintaining offline usage, both b/c it's generally lower priority most anything else and not an advertised feature. 

I'd highlight that we're putting a bandage a symptom here, not fixing the root cause which I generally don't like, but as long as we all are aware it seems ok in this instance until we know the root cause better.
