### ISSUE TITLE
Incorrect work of `getExplorerName` method.

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/zkapp-cli#456]
The [config.js:getExplorerName()](https://github.com/o1-labs/zkapp-cli/blob/c786dba747c4a0692fe7c7aa88b37dafcea8edcc/src/lib/config.js#L339) method will only work for certain cases. In other cases it will result in `undefined` link `explorer` query param value:

```shell
...

✔ Set the Mina GraphQL API URL to deploy to: · http://localhost:8282/graphql

...

Success!

Next steps:
  - If this is a testnet, request tMINA at:
    https://faucet.minaprotocol.com/?address=B62qq6f3enRpmGsWBaJMstwQjQiRdAnyAZ6CbKrcJFgFidRnWZyJkje&?explorer=undefined
```

Maybe we should consider its removal?

**Comment by ymekuria** [comment]
Thanks for bringing this up. Good catch @shimkiv! I would like to keep the query param for now because we discussed using the query parameter in the faucet to show a consistent explorer link to users so they can view funded accounts. I will update the function to handle all cases or at least return a default param for now.

**Comment by ymekuria** [comment]
This function has been refactored.
