### ISSUE TITLE
Automate "zk config" if lightnet is in use

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/zkapp-cli#528]
During "zk deploy" we can ask users (or determine automatically) if they are willing to deploy against the local lightnet. In which case we can configure everything automatically, simplifying zkapp-cli usage even further.

**Comment by MartinMinkov** [comment]
This is my personal opinion but I would instead prefer altering config generation rather than how the logic for deployment works. My reasoning is that changes to the configuration are easy to understand since you can just read and piece together what will happen. Changing the logic for deploy seems like it'd obscure details if something was wrong or deeper understanding was needed.

I would like something like `zk config --lightnet` that handles the case for local config generation. Then `zk deploy` works exactly the same and the whole CLI flow doesn't change.

**Comment by ymekuria** [comment]
+1 to @MartinMinkov s approach. I would prefer to not modify the `zk deploy` flow.
